### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by banana7778** [lindalee-inlab/MCM#1]
作者您好！根据原论文，我去global dataset和Washington dataset网站分别浏览了一下，发现前者数据网站已经停止运行，后者提供的数据集下载后为xml页面，请问这两个公开数据集您是否有留档？希望能得到您的回复和分享，我的联系方式2739595866@qq.com

**Comment by lindalee-inlab** [comment]
Problem: Dataset Address

We have carefully checked the two dataset download links.
The global dataset download is at http://www.matejk.cz/map-matching to https://zenodo.org/record/57731 and the downloaded XML file is in dataset format, the source file is at the same link. Please read the original author's paper carefully.

The Washington dataset is at https://www.microsoft.com/en-us/research/publication/hidden-markov-map-matching-noise-sparseness/ as  Excel files.

**Both datasets are public datasets, so please be sure to properly cite the work of both authors in your paper.**

Thank you very much for your issue, as the code is a published paper belongs to the lab results, so next time please **contact the corresponding author of the paper**.

**Comment by lindalee-inlab** [comment]
Links are available.
